### ISSUE TITLE
IMPORTANT!!: Check if Docusafe is responsible for the data lost

### ISSUE THREAD

**Issue by DoraNziali** [adorsys/datasafe#28]
The saved documents have been lost in DFS. This means that when the data is called up, the exception : "no Documents guard" always appears and the files are empty. Therefore Consumer could not act for 6 weeks. Please check if it is a fault of Docusafe1 or not.

**Comment by francis-pouatcha** [comment]
Please do not use customer name in a public ticket.

**Comment by electronicpeter** [comment]
Not data gets lost, but the document guard, that contains the key of the encryption. The whole docusafe source code has no method to delete a document guard. But datev calls destroy user and it seems highly probable that the user is destroyed by them. For docusafe exist tests with 100 user working in parallel. This problem never ever appeared. Datev was not able to switch on traces yet, because their are getting to much input. 
Here another aproach to log the releavant method:
1) use logback with a configuration filter:
'''
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>
                %d{HH:mm:ss.SSS} STDOUT [%thread] %-5level %logger{36} - %msg%n
            </pattern>
        </encoder>
    </appender>

    <appender name="FILTERED" class="ch.qos.logback.core.ConsoleAppender">
        <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
            <evaluator> 
                <expression>return message.contains("internalRemoveMultiple");</expression>
            </evaluator>
            <OnMismatch>DENY</OnMismatch>
            <OnMatch>NEUTRAL</OnMatch>
        </filter>
        <encoder>
            <pattern>
                %-4relative [%thread] %-5level %logger - %msg%n
            </pattern>
        </encoder>
    </appender>

    <logger name="org.adorsys.cryptoutils.extendendstoreconnection.impl.amazons3.RealAmazonS3ExtendedStoreConnection" level="DEBUG">
        <appender-ref ref="FILTERED" />
    </logger>

    
</configuration>
'''
and the following dependencies in maven
'''
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j-simple.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.7</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.1.7</version>
        </dependency>
        <dependency>
            <groupId>janino</groupId>
            <artifactId>janino</artifactId>
            <version>2.5.10</version>
        </dependency>
'''

**Comment by igrex** [comment]
> Not data gets lost, but the document guard, that contains the key of the encryption. The whole docusafe source code has no method to delete a document guard. But client calls destroy user and it seems highly probable that the user is destroyed by them. For docusafe exist tests with 100 user working in parallel. This problem never ever appeared. client was not able to switch on traces yet, because their are getting to much input.

It is true that we can force this behaviour by a client reset (`(DocumentSafeService#destroyUser(UserIDAuth userIDAuth))`) from within the webapp and a consequent call to the backend by the iOS App immediately after. But that is not the problem and also makes sense in a way as the iOS App is still within the users context. The real problem ist that this behaviour occurs constantly without resetting a user. This is the correct Exception: 

`de.datev.timp.application.controller.exceptions.ErrorKeyException : org.adorsys.docusafe.service.exceptions.NoDocumentGuardExists: BucketPath{bp-7405e638-91db-4754-bc7c-8bd15b678e52 - .keys/KS-7405e638-91db-4754-bc7c-8bd15b678e52.DK0d93dedf-5dfc-4ba5-b798-6216d76822bf} ... `

**Comment by electronicpeter** [comment]
Hi you all. Though we have not found the bug yet, I have another suggestion:
1) I would you the latest docusafe version, which is 0.5.22. This version does not work with document guards at all. Instead of document guards the documents are encrypted with the secret key of the keystore. I think, the problem will remain, but it is worth a try. (as far as we have understood the problem yet, is that the document that should be read contains metainformation that suggests a wrong key id. I have no explanation, how this can happen).
2) Rather than setting the log level for all classes to trace I strongly recommend only to set specific classes to debug, for example org.adorsys.docusafe.business.impl.DocumentSafeServiceImpl.

**Comment by igrex** [comment]
> 1. I would you the latest docusafe version, which is 0.5.22. This version does not work with document guards at all. Instead of document guards the documents are encrypted with the secret key of the keystore. I think, the problem will remain, but it is worth a try. (as far as we have understood the problem yet, is that the document that should be read contains metainformation that suggests a wrong key id. I have no explanation, how this can happen).

That is not really what I think, while debugging on a colleagues system who had the `NoDocumentGuardExists` with a locally running backend and a MINIO connection in OpenShift, we realized that it is the correct key file (document guard) that was missing. So the pair of content file and the corresponding document guard was not complete. 

And the upgrade of DocuSafe, as already explained, can not be done currently, as it is tied to the multibanking-docusafe-rest dependency v.1.3.1 that we are splitting up in an ongoing story. Part of that split is to upgrade DocuSafe, so this will happen as soon as possible.

**Comment by valb3r** [comment]
Outdated issue related to another project.
